title: "競技プログラミングライブラリ"
description: "競技プログラミング用のアルゴリズムライブラリ"
baseurl: "/kyoprolibrary"
url: "https://username.github.io"
theme: minima  #
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

include:
  - "*.cpp"
  - "*.md"

# ソースコードのディレクトリ設定
source: .

# プラグイン設定
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# ページナビゲーション設定
paginate: 5  # 1ページあたりのアイテム数

# その他の設定
permalink: pretty  # URLがわかりやすい形式になるよう設定
