theme: minima
markdown: kramdown
baseurl: "/kyoprolibrary"  # あなたのリポジトリ名に変更
url: "https://[GitHubユーザー名].github.io"

include:
  - "*.cpp"
  - "*.md"

defaults:
  - scope:
      path: "algorithms"
      type: "pages"
    values:
      layout: "algorithm"